# Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-ns

---

# Create Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-ns
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "mydb"
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "adminpassword"
  



---

# Create Pod
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-ns
spec:
  containers:
    - name: mysql-container
      image: mysql:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
